export const siteConfig = {
  name: "Arthur Buenaventura | Developer Portfolio",
  authorName: "Arthur Buenaventura",
  username: "rhtra",
  description:
    "Arthur Buenaventura's portfolio - A modern, responsive Next.js portfolio for developers.",
  url: "https://github.com/rhtra",
  links: {
    github: "https://github.com/rhtra",
  },
  keywords: [
    "Arthur Buenaventura",
    "Full Stack Developer",
    "Web Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Full stack developer portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
